### ISSUE TITLE
hops crashes when i hit run test

### ISSUE THREAD

**Issue by emranismail** [ExoWorldsSpies/hops#29]
whenever I hit run test i get errors in my terminal. I know the data is good because I used old data that has been processed through hops already and worked but now doesnt work aswell as all the new transits

any help will be GREATLY appreciated

Starting window:  HOPS - Fitting
C:\Astronomy\Anaconda_HOPS\Lib\site-packages\hops-3.1.2-py3.12.egg\hops\pylightcurve41\models\exoplanet_lc.py:555: UserWarning: PHOENIX models are only computed for solar metallicity stars. Setting stellar_metallicity = 0.
  warnings.warn('PHOENIX models are only computed for solar metallicity stars. Setting stellar_metallicity = 0.')
ERROR: invalid length= 2 for passbands_path (optional). It must have length=1.
ERROR: invalid length= 2 for output_path (optional). It must have length=1.

Fitting failed:
Traceback (most recent call last):
  File "C:\Astronomy\Anaconda_HOPS\Lib\site-packages\hops-3.1.2-py3.12.egg\hops\application.py", line 360, in fitting
    fitting_window.run(f_after=fitting_window.preview_figure.adjust_size)
  File "C:\Astronomy\Anaconda_HOPS\Lib\site-packages\hops-3.1.2-py3.12.egg\hops\application_windows.py", line 204, in run
    self.loop(f_after)
  File "C:\Astronomy\Anaconda_HOPS\Lib\site-packages\hops-3.1.2-py3.12.egg\hops\application_windows.py", line 191, in loop
    self.root.mainloop()
  File "C:\Astronomy\Anaconda_HOPS\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
  File "C:\Astronomy\Anaconda_HOPS\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Astronomy\Anaconda_HOPS\Lib\tkinter\__init__.py", line 862, in callit
    func(*args)
  File "C:\Astronomy\Anaconda_HOPS\Lib\site-packages\hops-3.1.2-py3.12.egg\hops\application_windows.py", line 109, in internal_command
    function()
  File "C:\Astronomy\Anaconda_HOPS\Lib\site-packages\hops-3.1.2-py3.12.egg\hops\application_6_fitting.py", line 410, in run_test
    planet, fitting = self.call_plc_fitting(optimiser='curve_fit')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Astronomy\Anaconda_HOPS\Lib\site-packages\hops-3.1.2-py3.12.egg\hops\application_6_fitting.py", line 638, in call_plc_fitting
    return planet, planet.transit_fitting(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Astronomy\Anaconda_HOPS\Lib\site-packages\hops-3.1.2-py3.12.egg\hops\pylightcurve41\models\exoplanet.py", line 526, in transit_fitting
    ldc1, ldc2, ldc3, ldc4 = self.ldcs(phot_filter, method=method, stellar_model=stellar_model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Astronomy\Anaconda_HOPS\Lib\site-packages\hops-3.1.2-py3.12.egg\hops\pylightcurve41\models\exoplanet.py", line 185, in ldcs
    return get_filter(filter_name).ldcs(self.stellar_logg, self.stellar_temperature, self.stellar_metallicity, wlrange, method, stellar_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Astronomy\Anaconda_HOPS\Lib\site-packages\hops-3.1.2-py3.12.egg\hops\pylightcurve41\models\exoplanet.py", line 60, in ldcs
    calc = exotethys(
           ^^^^^^^^^^
  File "C:\Astronomy\Anaconda_HOPS\Lib\site-packages\hops-3.1.2-py3.12.egg\hops\pylightcurve41\models\exoplanet_lc.py", line 616, in exotethys
    sail.ldc_calculate(parameters_file)
  File "C:\Astronomy\Anaconda_HOPS\Lib\site-packages\exotethys\sail.py", line 2395, in ldc_calculate
    [check, input_dict] = check_configuration(input_dict1) #Checking configuration file and partial dictionary update
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Astronomy\Anaconda_HOPS\Lib\site-packages\exotethys\sail.py", line 1532, in check_configuration
    exit()
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: None

**Comment by bribon2** [comment]
I have the same problem...
When I press TEST I get the same errors and the software doesn't progress...
Have you found a solution?

**Comment by emranismail** [comment]
I unfortunately have not, not sure what to do....

**Comment by bribon2** [comment]
I have another PC that works without any problem, but this happens to me on my laptop

**Comment by emranismail** [comment]
Thats interesting, on my desktop it just wont work, but works fine mostly on my laptop. This error also only started occuring after i upgraded my desktop and had to start fresh
