### ISSUE TITLE
No known catalog can be found

### ISSUE THREAD

**Issue by ppapadeas** [ExoWorldsSpies/hops#4]
After installing on a clean virtualenv with Python 3.8.3, trying to run hops.py fails with

```
Loading... Please wait for the main window to appear.
/home/liknus/git/envs/hops/lib/python3.8/site-packages/astroquery-0.4.2.dev0-py3.8.egg/astroquery/simbad/core.py:135: UserWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): '4': No known catalog could be found
  warnings.warn("Warning: The script line number %i raised "
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/liknus/git/envs/hops/lib/python3.8/site-packages/hops-2.6.1-py3.8.egg/hops/__main__.py", line 7, in <module>
    hops.run_app()
  File "/home/liknus/git/envs/hops/lib/python3.8/site-packages/hops-2.6.1-py3.8.egg/hops/__run__.py", line 2176, in run_app
    hops.run()
  File "/home/liknus/git/envs/hops/lib/python3.8/site-packages/hops-2.6.1-py3.8.egg/hops/__run__.py", line 2163, in run
    ReductionWindow(self)
  File "/home/liknus/git/envs/hops/lib/python3.8/site-packages/hops-2.6.1-py3.8.egg/hops/__run__.py", line 55, in __init__
    self.observing_planner = ObservingPlanner()
  File "/home/liknus/git/envs/hops/lib/python3.8/site-packages/hops-2.6.1-py3.8.egg/hops/hops_tools/observing_planner.py", line 350, in __init__
    self.update_window()
  File "/home/liknus/git/envs/hops/lib/python3.8/site-packages/hops-2.6.1-py3.8.egg/hops/hops_tools/observing_planner.py", line 384, in update_window
    result_table = Simbad.query_object(self.skyobject.get())[0]
TypeError: 'NoneType' object is not subscriptable
```

Ideas?

**Comment by Ross-Dobson** [comment]
Same problem trying to run hops.sh with Python 3.7.7, Ubuntu 20.04 LTS, AstroPy 4.0.1, also trying a fresh install of hops. I tried deleting my cache given by `Simbad.cache_location` in Python, as some similar issues online were cache problems, but this had no effect.

**Comment by capape** [comment]
Same problem here. It worked only after installation, next day this problem arised.

**Comment by atsiaras** [comment]
I have implemented a fix in version 2.6.6. Could you please try re-installing?

**Comment by capape** [comment]
It's working!
Thank you very much.

**Comment by Ross-Dobson** [comment]
Fixed for me too.
