### ISSUE TITLE
Unable to install in Debian 10

### ISSUE THREAD

**Issue by capape** [ExoWorldsSpies/hops#5]
Hi,

I've tried to install HOPS in Debian 10. First I tried to install with debian packaged python 3.7. It fails. Then I've tried to install after install anaconda for my user. 
`
It fails too. If I run it with sudo conflicts with debian packaged python 3.7. I can't find clear installation instructions on HOPS site about how to install on linux. I only can find to run linux-installer.sh script that is failing.

```
$  ./linux_installer.sh
running install
running bdist_egg
running egg_info
error: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/home/user/setup2_linux.py", line 3, in <module>
    from hops import __get_abspath__
ModuleNotFoundError: No module named 'hops'

```

```
$ sudo   ./linux_installer.sh
...
...
...
Using /usr/lib/python3/dist-packages
Finished processing dependencies for hops==2.6.4
Traceback (most recent call last):
  File "/root/setup2_linux.py", line 3, in <module>
    from hops import __get_abspath__
  File "/usr/local/lib/python3.7/dist-packages/hops-2.6.4-py3.7.egg/hops/__init__.py", line 5, in <module>
    from .__run__ import run_app
  File "/usr/local/lib/python3.7/dist-packages/hops-2.6.4-py3.7.egg/hops/__run__.py", line 22, in <module>
    from matplotlib.figure import Figure
  File "/usr/local/lib/python3.7/dist-packages/matplotlib-3.3.2-py3.7-linux-x86_64.egg/matplotlib/figure.py", line 18, in <module>
    from matplotlib import docstring, projections
  File "/usr/local/lib/python3.7/dist-packages/matplotlib-3.3.2-py3.7-linux-x86_64.egg/matplotlib/projections/__init__.py", line 4, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/__init__.py", line 1, in <module>
    from .axes3d import Axes3D
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/axes3d.py", line 42, in <module>
    class Axes3D(Axes):
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/axes3d.py", line 834, in Axes3D
    @docstring.dedent_interpd
  File "/usr/local/lib/python3.7/dist-packages/matplotlib-3.3.2-py3.7-linux-x86_64.egg/matplotlib/docstring.py", line 80, in dedent_interpd
    return interpd(func)
  File "/usr/local/lib/python3.7/dist-packages/matplotlib-3.3.2-py3.7-linux-x86_64.egg/matplotlib/docstring.py", line 40, in __call__
    func.__doc__ %= self.params
KeyError: 'scale'

```

**Comment by capape** [comment]
Well, I find out how to install this in debian linux.

1.- First create a python virtual env with:
python3 -m venv ${path_env_python }

Where ${path_env_python } is a folder where you have write access

2.- Activate that virtual env with 
source ${path_env_python }/bin/activate

3.- Run in this environment linux_installer
$ ./linux_installer.sh

4.- Create a hops.sh as this change 
`hops.sh 
#!/bin/bash

source  ${path_env_python }/bin/activate
python3 ${path_env_python }/lib/python3.7/site-packages/hops-2.6.4-py3.7.egg/hops
`

I hope this help.
